### ISSUE TITLE
comfyui support

### ISSUE THREAD

**Issue by ekswathi** [neph1/blender-stable-diffusion-render#1]
nice work bro. thank you
can we use comfyui interface, because it need low vram.

**Comment by neph1** [comment]
Thanks for trying it out. 

I can look into it, but I think it will require quite a bit of work. It doesn't seem so suitable as an api.
Have you tried SD forge? It might have the same api as auto111.

**Comment by neph1** [comment]
I did some reading. Might not be so hard after all. Will see what I can do.

**Comment by neph1** [comment]
There's now a branch that supports comfy: https://github.com/neph1/blender-stable-diffusion-render/pull/2
Not all settings supported yet, hope to finish it up tomorrow.
